import sys

def main():
    with open("rexc.asm", "w") as f:
        def w(l): f.write(l + "\n")

        w("; #############################################################################")
        w("; # Rex Compiler - Pure x86_64 Assembly")
        w("; #############################################################################")
        w("")
        w("%include \"common.inc\"")
        w("%include \"tokens.inc\"")
        w("")
        w("section .bss")
        w("    file_fd   resq 1")
        w("    file_buf  resb 1048576")
        w("    file_len  resq 1")
        w("    c_tok_t   resq 1")
        w("    c_tok_v   resq 1")
        w("    tok_v_str resb 4096")
        w("    src_p     resq 1")
        w("    src_e     resq 1")
        w("    ln_num    resq 1")
        w("    at_ls     resb 1")
        w("    ind_stk   resq 128")
        w("    ind_ptr   resq 1")
        w("    pen_d     resq 1")
        w("    s_tbl     resb 65536")
        w("    s_cnt     resq 1")
        w("    st_off    resq 1")
        w("    o_fd      resq 1")
        w("    rt_base   resq 1")
        w("    patch_stack resq 128")
        w("    patch_depth resq 1")
        w("    c_buf     resb 1048576")
        w("    c_ptr     resq 1")
        w("")
        w("section .data")
        w("    align 8")
        w("    e_hdr:")
        w("        db 0x7F, 'E', 'L', 'F', 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0")
        w("        dw 2")
        w("        dw 62")
        w("        dd 1")
        w("        dq 0x400080")
        w("        dq 64")
        w("        dq 0")
        w("        dd 0")
        w("        dw 64")
        w("        dw 56")
        w("        dw 1")
        w("        dw 0, 0, 0")
        w("    p_hdr:")
        w("        dd 1")
        w("        dd 7")
        w("        dq 0")
        w("        dq 0x400000")
        w("        dq 0x400000")
        w("        dq 0")
        w("        dq 0")
        w("        dq 0x1000")
        w("")
        w("    usage_msg db \"Usage: rexc <file.rex>\", 10")
        w("    usage_len equ $ - usage_msg")
        w("    o_nm db \"output\", 0")
        w("    kw_tbl:")
        w("        dq .s_out, TOK_OUTPUT")
        w("        dq .s_int, TOK_INT")
        w("        dq .s_if, TOK_IF")
        w("        dq .s_for, TOK_FOR")
        w("        dq .s_in, TOK_IN")
        w("        dq 0, 0")
        w("    .s_out db \"output\", 0")
        w("    .s_int db \"int\", 0")
        w("    .s_if  db \"if\", 0")
        w("    .s_for db \"for\", 0")
        w("    .s_in  db \"in\", 0")
        w("")
        w("section .text")
        w("    global _start")
        w("_start:")
        w("    pop rax")
        w("    cmp rax, 2")
        w("    jl .usage")
        w("    pop rax")
        w("    pop rdi")
        w("    mov rax, 2")
        w("    xor rsi, rsi")
        w("    syscall")
        w("    test rax, rax")
        w("    js .err")
        w("    mov [file_fd], rax")
        w("    mov rdi, rax")
        w("    mov rax, 0")
        w("    mov rsi, file_buf")
        w("    mov rdx, 1048576")
        w("    syscall")
        w("    mov [file_len], rax")
        w("    mov [src_p], rsi")
        w("    add rax, rsi")
        w("    mov [src_e], rax")
        w("    call rex_lex_init")
        w("    lea rax, [c_buf]")
        w("    mov [c_ptr], rax")
        w("    mov qword [patch_depth], 0")
        w("    call rex_parse")
        w("    mov rax, 60")
        w("    xor rdi, rdi")
        w("    syscall")
        w(".usage:")
        w("    mov rax, 1")
        w("    mov rdi, 1")
        w("    mov rsi, usage_msg")
        w("    mov rdx, usage_len")
        w("    syscall")
        w(".err:")
        w("    mov rax, 60")
        w("    mov rdi, 1")
        w("    syscall")
        w("")
        w("rex_lex_init:")
        w("    mov qword [ln_num], 1")
        w("    mov byte [at_ls], 1")
        w("    mov qword [pen_d], 0")
        w("    mov qword [ind_stk], 0")
        w("    lea rax, [ind_stk + 8]")
        w("    mov [ind_ptr], rax")
        w("    ret")
        w("")
        w("rex_lex_next:")
        w("    mov rax, [pen_d]")
        w("    test rax, rax")
        w("    jz .body")
        w("    dec qword [pen_d]")
        w("    sub qword [ind_ptr], 8")
        w("    mov rax, TOK_DEDENT")
        w("    ret")
        w(".body:")
        w("    mov rsi, [src_p]")
        w(".ws:")
        w("    cmp rsi, [src_e]")
        w("    jae .eof")
        w("    cmp byte [at_ls], 0")
        w("    jz .char")
        w("    xor rcx, rcx")
        w(".il:")
        w("    cmp rsi, [src_e]")
        w("    jae .id_blk")
        w("    mov al, [rsi]")
        w("    cmp al, ' '")
        w("    je .is")
        w("    cmp al, 9")
        w("    je .it")
        w("    jmp .id_blk")
        w(".is:")
        w("    inc rcx")
        w("    inc rsi")
        w("    jmp .il")
        w(".it:")
        w("    add rcx, 4")
        w("    inc rsi")
        w("    jmp .il")
        w(".id_blk:")
        w("    mov [src_p], rsi")
        w("    mov rbx, [ind_ptr]")
        w("    mov rdx, [rbx-8]")
        w("    cmp rcx, rdx")
        w("    je .char")
        w("    jg .ig")
        w("    xor rax, rax")
        w(".dl:")
        w("    sub rbx, 8")
        w("    mov rdx, [rbx-8]")
        w("    inc rax")
        w("    cmp rcx, rdx")
        w("    je .df")
        w("    jl .dl")
        w(".df:")
        w("    mov [ind_ptr], rbx")
        w("    mov [pen_d], rax")
        w("    dec qword [pen_d]")
        w("    mov rax, TOK_DEDENT")
        w("    ret")
        w(".ig:")
        w("    mov [rbx], rcx")
        w("    add qword [ind_ptr], 8")
        w("    mov rax, TOK_INDENT")
        w("    ret")
        w(".char:")
        w("    cmp rsi, [src_e]")
        w("    jae .eof")
        w("    mov al, [rsi]")
        w("    cmp al, ' '")
        w("    je .ip")
        w("    cmp al, 9")
        w("    je .ip")
        w("    cmp al, 10")
        w("    je .in")
        w("    cmp al, '#'")
        w("    je .ic")
        w("    mov byte [at_ls], 0")
        w("    cmp al, '\"'")
        w("    je .ls")
        w("    cmp al, \"'\"")
        w("    je .ls")
        w("    cmp al, ':'")
        w("    je .rc")
        w("    cmp al, '='")
        w("    je .ra")
        w("    cmp al, '.'")
        w("    je .rd")
        w("    call rex_is_alpha")
        w("    test rax, rax")
        w("    jnz .li")
        w("    call rex_is_digit")
        w("    test rax, rax")
        w("    jnz .ln")
        w("    inc rsi")
        w("    mov [src_p], rsi")
        w("    jmp .body")
        w(".ip:")
        w("    inc rsi")
        w("    mov [src_p], rsi")
        w("    jmp .ws")
        w(".in:")
        w("    inc rsi")
        w("    mov [src_p], rsi")
        w("    inc qword [ln_num]")
        w("    mov byte [at_ls], 1")
        w("    mov rax, TOK_NEWLINE")
        w("    ret")
        w(".ic:")
        w("    inc rsi")
        w(".cl:")
        w("    cmp rsi, [src_e]")
        w("    jae .eof")
        w("    cmp byte [rsi], 10")
        w("    je .in")
        w("    inc rsi")
        w("    jmp .cl")
        w(".rc:")
        w("    inc rsi")
        w("    mov [src_p], rsi")
        w("    mov rax, TOK_COLON")
        w("    ret")
        w(".ra:")
        w("    inc rsi")
        w("    mov [src_p], rsi")
        w("    mov rax, TOK_ASSIGN")
        w("    ret")
        w(".rd:")
        w("    inc rsi")
        w("    cmp byte [rsi], '.'")
        w("    je .r2")
        w("    mov [src_p], rsi")
        w("    mov rax, TOK_DOT")
        w("    ret")
        w(".r2:")
        w("    inc rsi")
        w("    mov [src_p], rsi")
        w("    mov rax, TOK_DOTDOT")
        w("    ret")
        w(".ls:")
        w("    mov dl, [rsi]")
        w("    inc rsi")
        w("    xor rcx, rcx")
        w(".sl:")
        w("    cmp rsi, [src_e]")
        w("    jae .sd")
        w("    mov al, [rsi]")
        w("    cmp al, dl")
        w("    je .sq")
        w("    mov [tok_v_str+rcx], al")
        w("    inc rcx")
        w("    inc rsi")
        w("    jmp .sl")
        w(".sq:")
        w("    inc rsi")
        w(".sd:")
        w("    mov [src_p], rsi")
        w("    mov byte [tok_v_str+rcx], 0")
        w("    mov [c_tok_v], rcx")
        w("    mov rax, TOK_LIT_STR")
        w("    ret")
        w(".li:")
        w("    xor rcx, rcx")
        w(".ll:")
        w("    mov al, [rsi]")
        w("    call rex_is_alnum")
        w("    test rax, rax")
        w("    jz .id_s")
        w("    mov [tok_v_str+rcx], al")
        w("    inc rcx")
        w("    inc rsi")
        w("    jmp .ll")
        w(".id_s:")
        w("    mov [src_p], rsi")
        w("    mov byte [tok_v_str+rcx], 0")
        w("    mov rsi, kw_tbl")
        w(".kl:")
        w("    mov rdi, [rsi]")
        w("    test rdi, rdi")
        w("    jz .nk")
        w("    push rsi")
        w("    lea rsi, [tok_v_str]")
        w("    call rex_strcmp")
        w("    pop rsi")
        w("    test rax, rax")
        w("    jnz .ik")
        w("    add rsi, 16")
        w("    jmp .kl")
        w(".ik:")
        w("    mov rax, [rsi+8]")
        w("    ret")
        w(".nk:")
        w("    mov rax, TOK_IDENT")
        w("    lea rdx, [tok_v_str]")
        w("    mov [c_tok_v], rdx")
        w("    ret")
        w(".ln:")
        w("    xor rbx, rbx")
        w(".nl:")
        w("    mov al, [rsi]")
        w("    call rex_is_digit")
        w("    test rax, rax")
        w("    jz .nd")
        w("    sub al, '0'")
        w("    movzx rax, al")
        w("    imul rbx, 10")
        w("    add rbx, rax")
        w("    inc rsi")
        w("    jmp .nl")
        w(".nd:")
        w("    mov [src_p], rsi")
        w("    mov rax, TOK_LIT_INT")
        w("    mov [c_tok_v], rbx")
        w("    ret")
        w(".eof:")
        w("    mov rax, TOK_EOF")
        w("    ret")
        w("")
        w("rex_is_alpha:")
        w("    mov al, [rsi]")
        w("    cmp al, 'a'")
        w("    jl .u")
        w("    cmp al, 'z'")
        w("    jle .y")
        w(".u:")
        w("    cmp al, 'A'")
        w("    jl .n")
        w("    cmp al, 'Z'")
        w("    jle .y")
        w(".n:")
        w("    cmp al, '_'")
        w("    je .y")
        w("    xor rax, rax")
        w("    ret")
        w(".y:")
        w("    mov rax, 1")
        w("    ret")
        w("rex_is_digit:")
        w("    mov al, [rsi]")
        w("    cmp al, '0'")
        w("    jl .dn")
        w("    cmp al, '9'")
        w("    jle .dy")
        w(".dn:")
        w("    xor rax, rax")
        w("    ret")
        w(".dy:")
        w("    mov rax, 1")
        w("    ret")
        w("rex_is_alnum:")
        w("    call rex_is_alpha")
        w("    test rax, rax")
        w("    jnz .ay")
        w("    call rex_is_digit")
        w(".ay: ret")
        w("rex_strcmp:")
        w(".l:")
        w("    mov al, [rsi]")
        w("    mov bl, [rdi]")
        w("    cmp al, bl")
        w("    jne .sn")
        w("    test al, al")
        w("    jz .sy")
        w("    inc rsi")
        w("    inc rdi")
        w("    jmp .l")
        w(".sn:")
        w("    xor rax, rax")
        w("    ret")
        w(".sy:")
        w("    mov rax, 1")
        w("    ret")
        w("rex_strcpy:")
        w(".l:")
        w("    lodsb")
        w("    stosb")
        w("    test al, al")
        w("    jnz .l")
        w("    ret")
        w("")
        w("rex_get_va:")
        w("    mov rax, [c_ptr]")
        w("    lea rbx, [c_buf]")
        w("    sub rax, rbx")
        w("    add rax, 0x400080")
        w("    ret")
        w("")
        w("rex_parse:")
        w("    mov qword [s_cnt], 0")
        w("    mov qword [st_off], 8")
        w("    mov rdi, 0xE9")
        w("    call rex_eb")
        w("    mov rax, [c_ptr]")
        w("    push rax")
        w("    xor rdi, rdi")
        w("    call rex_edq32")
        w("    call rex_get_va")
        w("    add rax, 15")
        w("    and rax, ~15")
        w("    mov rdx, rax")
        w("    lea rbx, [c_buf]")
        w("    sub rax, 0x400080")
        w("    add rax, rbx")
        w("    mov [c_ptr], rax")
        w("    mov [rt_base], rdx")
        w("    lea rsi, [rt_start]")
        w("    mov rcx, rt_end-rt_start")
        w(".em: lodsb")
        w("    movzx rdi, al")
        w("    push rsi")
        w("    push rcx")
        w("    call rex_eb")
        w("    pop rcx")
        w("    pop rsi")
        w("    loop .em")
        w("    pop rdi")
        w("    call rex_get_va")
        w("    mov rsi, rax")
        w("    call rex_patch_at_ptr")
        w("    mov rdi, 0x55")
        w("    call rex_eb")
        w("    mov rdi, 0x48")
        w("    call rex_eb")
        w("    mov rdi, 0x89")
        w("    call rex_eb")
        w("    mov rdi, 0xE5")
        w("    call rex_eb")
        w("    call rex_adv")
        w(".ml: mov rax, [c_tok_t]")
        w("    cmp rax, TOK_EOF")
        w("    je .dn")
        w("    cmp rax, TOK_NEWLINE")
        w("    je .sk")
        w("    call rex_p_stmt")
        w("    jmp .ml")
        w(".sk: call rex_adv")
        w("    jmp .ml")
        w(".dn:")
        w("    mov rdi, 0x48")
        w("    call rex_eb")
        w("    mov rdi, 0x89")
        w("    call rex_eb")
        w("    mov rdi, 0xEC")
        w("    call rex_eb")
        w("    mov rdi, 0x5D")
        w("    call rex_eb")
        w("    mov rdi, 60")
        w("    call rex_emrax")
        w("    xor rdi, rdi")
        w("    call rex_emrdi")
        w("    mov rdi, 0x0F")
        w("    call rex_eb")
        w("    mov rdi, 0x05")
        w("    call rex_eb")
        w("    call rex_finish")
        w("    ret")
        w("")
        w("rex_p_stmt:")
        w("    mov rax, [c_tok_t]")
        w("    cmp rax, TOK_OUTPUT")
        w("    je rex_p_out")
        w("    cmp rax, TOK_INT")
        w("    je rex_p_decl")
        w("    cmp rax, TOK_COLON")
        w("    je rex_p_mut")
        w("    cmp rax, TOK_IF")
        w("    je rex_p_if")
        w("    cmp rax, TOK_FOR")
        w("    je rex_p_for")
        w("    call rex_adv")
        w("    ret")
        w("")
        w("rex_p_decl:")
        w("    call rex_adv")
        w("    sub rsp, 64")
        w("    mov rsi, [c_tok_v]")
        w("    mov rdi, rsp")
        w("    call rex_strcpy")
        w("    call rex_adv")
        w("    mov rsi, rsp")
        w("    call f_sym")
        w("    test rax, rax")
        w("    jnz .ex")
        w("    mov rax, [s_cnt]")
        w("    imul rax, 64")
        w("    lea rbx, [s_tbl]")
        w("    add rbx, rax")
        w("    mov rsi, rsp")
        w("    mov rdi, rbx")
        w("    mov rcx, 32")
        w("    rep movsb")
        w("    mov qword [rbx+32], 0")
        w("    mov rdx, [st_off]")
        w("    mov [rbx+40], rdx")
        w("    add qword [st_off], 8")
        w("    inc qword [s_cnt]")
        w("    mov rdi, 0x48")
        w("    call rex_eb")
        w("    mov rdi, 0x83")
        w("    call rex_eb")
        w("    mov rdi, 0xEC")
        w("    call rex_eb")
        w("    mov rdi, 0x08")
        w("    call rex_eb")
        w(".ex: add rsp, 64")
        w("    ret")
        w("")
        w("rex_p_mut:")
        w("    call rex_adv")
        w("    sub rsp, 64")
        w("    mov rsi, [c_tok_v]")
        w("    mov rdi, rsp")
        w("    call rex_strcpy")
        w("    call rex_adv")
        w("    call rex_adv")
        w("    call rex_p_exp")
        w("    mov rsi, rsp")
        w("    call f_sym")
        w("    test rax, rax")
        w("    jz .mut_ex")
        w("    mov rbx, rax")
        w("    mov rdx, [rbx+40]")
        w("    mov rdi, 0x48")
        w("    call rex_eb")
        w("    mov rdi, 0x89")
        w("    call rex_eb")
        w("    mov rdi, 0x45")
        w("    call rex_eb")
        w("    neg rdx")
        w("    mov rdi, rdx")
        w("    call rex_eb")
        w(".mut_ex: add rsp, 64")
        w("    ret")
        w("")
        w("rex_p_out:")
        w("    call rex_adv")
        w("    call rex_p_exp")
        w("    mov rdi, (rt_pri - rt_start)")
        w("    call rex_eca_va")
        w("    ret")
        w("")
        w("rex_p_exp:")
        w("    mov rax, [c_tok_t]")
        w("    cmp rax, TOK_LIT_INT")
        w("    je .li")
        w("    cmp rax, TOK_IDENT")
        w("    je .id")
        w("    ret")
        w(".li: mov rdi, [c_tok_v]")
        w("    call rex_emrax")
        w("    call rex_adv")
        w("    ret")
        w(".id: mov rsi, [c_tok_v]")
        w("    call f_sym")
        w("    test rax, rax")
        w("    jz .ie")
        w("    mov rbx, rax")
        w("    mov rdx, [rbx+40]")
        w("    mov rdi, 0x48")
        w("    call rex_eb")
        w("    mov rdi, 0x8B")
        w("    call rex_eb")
        w("    mov rdi, 0x45")
        w("    call rex_eb")
        w("    neg rdx")
        w("    mov rdi, rdx")
        w("    call rex_eb")
        w(".ie: call rex_adv")
        w("    ret")
        w("")
        w("rex_p_if:")
        w("    call rex_adv")
        w("    call rex_p_exp")
        w("    mov rdi, 0x48")
        w("    call rex_eb")
        w("    mov rdi, 0x85")
        w("    call rex_eb")
        w("    mov rdi, 0xC0")
        w("    call rex_eb")
        w("    mov rdi, 0x0F")
        w("    call rex_eb")
        w("    mov rdi, 0x84")
        w("    call rex_eb")
        w("    mov rax, [c_ptr]")
        w("    call rex_patch_push")
        w("    xor rdi, rdi")
        w("    call rex_edq32")
        w("    call rex_adv")
        w("    call rex_adv")
        w(".if_l: mov rax, [c_tok_t]")
        w("    cmp rax, TOK_DEDENT")
        w("    je .if_dn")
        w("    cmp rax, TOK_EOF")
        w("    je .if_dn")
        w("    cmp rax, TOK_NEWLINE")
        w("    je .if_sk")
        w("    call rex_p_stmt")
        w("    jmp .if_l")
        w(".if_sk: call rex_adv")
        w("    jmp .if_l")
        w(".if_dn: call rex_adv")
        w("    call rex_patch_pop_and_patch")
        w("    ret")
        w("")
        w("rex_p_for:")
        w("    call rex_adv")
        w("    sub rsp, 64")
        w("    mov rsi, [c_tok_v]")
        w("    mov rdi, rsp")
        w("    call rex_strcpy")
        w("    call rex_adv")
        w("    call rex_adv")
        w("    call rex_p_exp")
        w("    mov rsi, rsp")
        w("    call f_sym")
        w("    test rax, rax")
        w("    jz .for_er")
        w("    mov rbx, rax")
        w("    mov rdx, [rbx+40]")
        w("    push rdx")
        w("    mov rdi, 0x48")
        w("    call rex_eb")
        w("    mov rdi, 0x89")
        w("    call rex_eb")
        w("    mov rdi, 0x45")
        w("    call rex_eb")
        w("    neg rdx")
        w("    mov rdi, rdx")
        w("    call rex_eb")
        w("    call rex_adv")
        w("    call rex_p_exp")
        w("    mov rdi, 0x50")
        w("    call rex_eb")
        w("    call rex_get_va")
        w("    push rax")
        w("    call rex_adv")
        w("    call rex_adv")
        w(".for_l: mov rax, [c_tok_t]")
        w("    cmp rax, TOK_DEDENT")
        w("    je .for_dn")
        w("    cmp rax, TOK_EOF")
        w("    je .for_dn")
        w("    cmp rax, TOK_NEWLINE")
        w("    je .for_sk")
        w("    call rex_p_stmt")
        w("    jmp .for_l")
        w(".for_sk: call rex_adv")
        w("    jmp .for_l")
        w(".for_dn: call rex_adv")
        w("    pop rbx")
        w("    pop rdx")
        w("    mov rdi, 0x48")
        w("    call rex_eb")
        w("    mov rdi, 0x83")
        w("    call rex_eb")
        w("    mov rdi, 0x45")
        w("    call rex_eb")
        w("    neg rdx")
        w("    mov rdi, rdx")
        w("    call rex_eb")
        w("    mov rdi, 1")
        w("    call rex_eb")
        w("    mov rdi, 0x48")
        w("    call rex_eb")
        w("    mov rdi, 0x8B")
        w("    call rex_eb")
        w("    mov rdi, 0x45")
        w("    call rex_eb")
        w("    neg rdx")
        w("    mov rdi, rdx")
        w("    call rex_eb")
        w("    mov rdi, 0x48")
        w("    call rex_eb")
        w("    mov rdi, 0x3B")
        w("    call rex_eb")
        w("    mov rdi, 0x04")
        w("    call rex_eb")
        w("    mov rdi, 0x24")
        w("    call rex_eb")
        w("    mov rdi, 0x0F")
        w("    call rex_eb")
        w("    mov rdi, 0x8E")
        w("    call rex_eb")
        w("    call rex_get_va")
        w("    add rax, 4")
        w("    mov rcx, rbx")
        w("    sub rcx, rax")
        w("    mov rdi, rcx")
        w("    call rex_edq32")
        w("    mov rdi, 0x58")
        w("    call rex_eb")
        w(".for_er: add rsp, 64")
        w("    ret")
        w("")
        w("rex_eb: mov rdx, [c_ptr]")
        w("    mov [rdx], dil")
        w("    inc qword [c_ptr]")
        w("    ret")
        w("rex_edq32: mov rdx, [c_ptr]")
        w("    mov [rdx], edi")
        w("    add qword [c_ptr], 4")
        w("    ret")
        w("rex_edq: mov rdx, [c_ptr]")
        w("    mov [rdx], rdi")
        w("    add qword [c_ptr], 8")
        w("    ret")
        w("rex_emrax: push rdi")
        w("    mov rdi, 0x48")
        w("    call rex_eb")
        w("    mov rdi, 0xB8")
        w("    call rex_eb")
        w("    pop rdi")
        w("    call rex_edq")
        w("    ret")
        w("rex_emrdi: push rdi")
        w("    mov rdi, 0x48")
        w("    call rex_eb")
        w("    mov rdi, 0xBF")
        w("    call rex_eb")
        w("    pop rdi")
        w("    call rex_edq")
        w("    ret")
        w("rex_eca_va: push rdi")
        w("    mov rdi, 0xE8")
        w("    call rex_eb")
        w("    call rex_get_va")
        w("    add rax, 4")
        w("    mov rdx, [rt_base]")
        w("    pop rdi")
        w("    add rdx, rdi")
        w("    sub rdx, rax")
        w("    mov rdi, rdx")
        w("    call rex_edq32")
        w("    ret")
        w("rex_patch_at_ptr: push rax")
        w("    push rbx")
        w("    push rdx")
        w("    mov rax, rdi")
        w("    lea rbx, [c_buf]")
        w("    sub rax, rbx")
        w("    add rax, 0x400080")
        w("    add rax, 4")
        w("    mov rbx, rsi")
        w("    sub rbx, rax")
        w("    mov [rdi], ebx")
        w("    pop rdx")
        w("    pop rbx")
        w("    pop rax")
        w("    ret")
        w("rex_patch_push: mov rbx, [patch_depth]")
        w("    lea rcx, [patch_stack]")
        w("    mov [rcx + rbx*8], rax")
        w("    inc qword [patch_depth]")
        w("    ret")
        w("rex_patch_pop_and_patch: dec qword [patch_depth]")
        w("    mov rbx, [patch_depth]")
        w("    lea rcx, [patch_stack]")
        w("    mov rdi, [rcx + rbx*8]")
        w("    call rex_get_va")
        w("    mov rsi, rax")
        w("    call rex_patch_at_ptr")
        w("    ret")
        w("rex_adv: call rex_lex_next")
        w("    mov [c_tok_t], rax")
        w("    ret")
        w("f_sym: mov rcx, [s_cnt]")
        w("    xor rdx, rdx")
        w(".f_l: test rcx, rcx")
        w("    jz .f_n")
        w("    mov rax, rdx")
        w("    imul rax, 64")
        w("    lea rbx, [s_tbl]")
        w("    add rbx, rax")
        w("    push rsi")
        w("    push rbx")
        w("    push rcx")
        w("    push rdx")
        w("    mov rdi, rbx")
        w("    call rex_strcmp")
        w("    pop rdx")
        w("    pop rcx")
        w("    pop rbx")
        w("    pop rsi")
        w("    test rax, rax")
        w("    jnz .f_f")
        w("    inc rdx")
        w("    dec rcx")
        w("    jmp .f_l")
        w(".f_f: mov rax, rbx")
        w("    ret")
        w(".f_n: xor rax, rax")
        w("    ret")
        w("rex_finish:")
        w("    lea rax, [c_buf]")
        w("    mov rdx, [c_ptr]")
        w("    sub rdx, rax")
        w("    add rdx, 128")
        w("    mov [p_hdr+32], rdx")
        w("    mov [p_hdr+40], rdx")
        w("    mov rax, 2")
        w("    mov rdi, o_nm")
        w("    mov rsi, 577")
        w("    mov rdx, 0755o")
        w("    syscall")
        w("    mov [o_fd], rax")
        w("    mov rdi, rax")
        w("    mov rax, 1")
        w("    mov rsi, e_hdr")
        w("    mov rdx, 64")
        w("    syscall")
        w("    mov rdi, [o_fd]")
        w("    mov rax, 1")
        w("    mov rsi, p_hdr")
        w("    mov rdx, 56")
        w("    syscall")
        w("    mov rdi, [o_fd]")
        w("    mov rax, 1")
        w("    xor rbx, rbx")
        w("    push rbx")
        w("    mov rsi, rsp")
        w("    mov rdx, 8")
        w("    syscall")
        w("    pop rbx")
        w("    mov rdi, [o_fd]")
        w("    mov rax, 1")
        w("    lea rsi, [c_buf]")
        w("    mov rdx, [c_ptr]")
        w("    lea rbx, [c_buf]")
        w("    sub rdx, rbx")
        w("    syscall")
        w("    mov rax, 3")
        w("    mov rdi, [o_fd]")
        w("    syscall")
        w("    ret")
        w("")
        w("rt_start:")
        w("rt_pri: push rbp")
        w("    mov rbp, rsp")
        w("    push rbx")
        w("    sub rsp, 64")
        w("    mov rbx, 10")
        w("    lea rcx, [rbp-1]")
        w("    mov byte [rcx], 10")
        w("    test rax, rax")
        w("    jnz .rt_nz")
        w("    dec rcx")
        w("    mov byte [rcx], '0'")
        w("    jmp .rt_pr")
        w(".rt_nz: xor rdx, rdx")
        w("    div rbx")
        w("    add dl, '0'")
        w("    dec rcx")
        w("    mov [rcx], dl")
        w("    test rax, rax")
        w("    jnz .rt_nz")
        w(".rt_pr: mov rax, 1")
        w("    mov rdi, 1")
        w("    mov rsi, rcx")
        w("    mov rdx, rbp")
        w("    sub rdx, rcx")
        w("    syscall")
        w("    add rsp, 64")
        w("    pop rbx")
        w("    pop rbp")
        w("    ret")
        w("rt_end:")

if __name__ == \"__main__\":
    main()
