seq[int] nums = [10, 20, 30, 40, 50]

output(nums.first())
output(nums.last())
output(nums.len())
output(nums.cap())
output(nums.is_empty())
output(nums.contains(30))
output(nums.contains(99))
output(nums.index_of(40))
output(nums.sum())
output(nums.min())
output(nums.max())

:nums.reverse()
output(nums.first())
output(nums.last())
output(nums.len())

seq[int] sl = nums.slice(1, 3)
output(sl.len())
output(sl.get(0))
output(sl.get(1))
seq[int] s2 = nums.slice(3, 99)
output(s2.len())
output(s2.get(0))
seq[int] s3 = nums.slice(9, 2)
output(s3.len())

:nums.clear()
output(nums.len())
output(nums.is_empty())

seq[int] a = [5, 3, 8, 1]
output(a.sum())
output(a.min())
output(a.max())
output(a.contains(8))
output(a.first())
output(a.last())
