// test_file_io.rex — file I/O (design.md §15.4)
str path = "/tmp/rex_test_io.txt"
output(file_exists("/tmp/rex_never_exists_xyz_42.txt"))

f = open(path, "w")
f.writeln("hello")
f.writeln("world")
f.flush()
output(f.path())
f.close()

f = open(path, "r")
output(f.read())
f.close()
output(file_exists(path))

f = open(path)
str a = f.read_line()
output(a)
str b = f.read_line()
output(b)
f.close()

f = open(path)
seq[byte] c = f.read_all_bytes()
output(c.len())
f.close()

str d = open(path).read()
output(d)

f = open(path, "w")
f.write("abc")
f.close()
output(open(path).read())

f = open(path, "wb")
f.write_bytes([65, 66, 67, 10])
f.close()
seq[byte] e = open(path).read_all_bytes()
output(e.len())
output(e[0])
output(e[1])
output(e[2])
output(e[3])

f = open(path)
seq[byte] rb = f.read_bytes(2)
output(rb.len())
output(rb[0])
output(rb[1])
f.close()

f = open(path, "w")
f.writeln("aa")
f.writeln("bb")
f.writeln("cc")
f.close()
f = open(path)
seq[str] ls = f.lines()
output(ls.len())
output(ls[0])
output(ls[1])
output(ls[2])
f.close()

f = open(path)
f.seek(2)
output(f.pos())
output(f.size())
str h = f.read_line()
output(h)
f.seek_end(3)
output(f.pos())
str i = f.read_line()
output(i)
f.seek_end()
output(f.pos())
output(f.is_eof())
str eof_line = f.read_line()
output(eof_line)
output(f.is_eof())
f.close()

f = open(path, "w")
f.writeln("x")
f.close()
output(open(path).read())
output(file_exists(path))

output(file_exists("/tmp/rex_does_not_exist_xyz.txt"))

with open(path, "a") as aw:
    aw.writeln("y")
f = open(path)
str g = f.read()
output(g)
f.close()
